export const TIPOS_MANTENIMIENTO = [
  'Cambio de aceite',
  'Filtro de aire',
  'Filtro de aceite',
  'Filtro de habitáculo',
  'Pastillas de freno',
  'Discos de freno',
  'Rotación de neumáticos',
  'Cambio de neumáticos',
  'ITV',
  'Batería',
  'Correa de distribución',
  'Embrague',
  'Refrigerante',
  'Líquido de frenos',
  'Alineación',
  'Dirección',
  'Revisión general',
  'Renovación seguro',
  'Inspección de luces',
  'Limpieza de inyectores',
  'Otros',
]
